
networks:
  apicore-net:
    driver: bridge

services:
  mysql:
    image: mysql:9
    container_name: server-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: apicore
      MYSQL_USER: sfapp_user
      MYSQL_PASSWORD: sfapp_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - apicore-net

  redis:
    image: redis:alpine
    container_name: server-cache
    restart: unless-stopped
    networks:
      - apicore-net

  php:
    build:
      context: ./docker/php
    container_name: server-php
    restart: unless-stopped
    volumes:
      - ./apicore:/var/www/apicore
    working_dir: /var/www/apicore
    depends_on:
      - mysql
      - redis
    networks:
      - apicore-net

  nginx:
    image: nginx:alpine
    container_name: server-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./apicore:/var/www/apicore
    depends_on:
      - php
    networks:
      - apicore-net
